### ISSUE TITLE
Upgrade etherpad on pad.webmaker.org to most current version

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-lightsaber#1]

**Comment by jdotpz** [comment]
Following their directions on the (github page)[https://github.com/ether/etherpad-lite] for etherpad results in:
http://pastebin.mozilla.org/8263959

I've tweeted over to etherpad to see if they have a later version debian build packaged already that maybe doesn't have a boatload of missing packages.

**Comment by JohnMcLear** [comment]
Can you assign this to me please @jdotpz ?

**Comment by JohnMcLear** [comment]
@jdotpz I put packages to literal versions last night, `git pull origin develop` and see if it fixes it for you.

Those errors aren't coming from EP, they are coming from NPM :|

**Comment by OpenMatt** [comment]
@jdotpz: helpful summary of what's new in 1.5: http://mclear.co.uk/2015/01/03/finally-releasing-etherpad-1-5/

**Comment by jdotpz** [comment]
Awesome @JohnMcLear and many thanks for the help!  You are all sorts of heroic.  
I'm going to crank on this today, and I'll roll you cats a .deb from the latest branch if I can get it cookin'.

![swagactivate](https://cloud.githubusercontent.com/assets/1373628/5838123/a6ae2ab8-a14a-11e4-8838-694d300fd129.gif)

**Comment by jdotpz** [comment]
Hmmm, still bombing on the dependencies.  
http://pastebin.mozilla.org/8274853

It's odd, because I see nowhere inside the directory structure where '^1.0.7' exists as text.  _scratches head, refills coffee_

**Comment by JohnMcLear** [comment]
Pull and try that..

**Comment by jdotpz** [comment]
Ah, fixed that one!  We've got a new one though!

assert-plus is doing the same thing.

ubuntu@i-0134faed:~/etherpad-lite$ grep -C10 assert-plus ./src/npm-debug.log 
1037 silly resolved     contributors: [ [Object], [Object] ],
1037 silly resolved     repository:
1037 silly resolved      { type: 'git',
1037 silly resolved        url: 'git://github.com/joyent/node-http-signature.git' },
1037 silly resolved     homepage: 'https://github.com/joyent/node-http-signature/',
1037 silly resolved     bugs: 'https://github.com/joyent/node-http-signature/issues',
1037 silly resolved     keywords: [ 'https', 'request' ],
1037 silly resolved     engines: { node: '>=0.8' },
1037 silly resolved     main: 'lib/index.js',
1037 silly resolved     scripts: { test: 'tap test/*.js' },
1037 silly resolved     dependencies: { 'assert-plus': '^0.1.5', asn1: '0.1.11', ctype: '0.5.3' },
1037 silly resolved     devDependencies: { 'node-uuid': '^1.4.1', tap: '0.4.2' },
1037 silly resolved     readme: '# node-http-signature\n\nnode-http-signature is a node.js library that has client and server components\nfor Joyent\'s [HTTP Signature Scheme](http_signing.md).\n\n## Usage\n\nNote the example below signs a request with the same key/cert used to start an\nHTTP server. This is almost certainly not what you actually want, but is just\nused to illustrate the API calls; you will need to provide your own key\nmanagement in addition to this library.\n\n### Client\n\n`js\nvar fs = require(\'fs\');\nvar https = require(\'https\');\nvar httpSignature = require(\'http-signature\');\n\nvar key = fs.readFileSync(\'./key.pem\', \'ascii\');\n\nvar options = {\n  host: \'localhost\',\n  port: 8443,\n  path: \'/\',\n  method: \'GET\',\n  headers: {}\n};\n\n// Adds a \'Date\' header in, signs it, and adds the\n// \'Authorization\' header in.\nvar req = https.request(options, function(res) {\n  console.log(res.statusCode);\n});\n\n\nhttpSignature.sign(req, {\n  key: key,\n  keyId: \'./cert.pem\'\n});\n\nreq.end();\n`\n\n### Server\n\n`js\nvar fs = require(\'fs\');\nvar https = require(\'https\');\nvar httpSignature = require(\'http-signature\');\n\nvar options = {\n  key: fs.readFileSync(\'./key.pem\'),\n  cert: fs.readFileSync(\'./cert.pem\')\n};\n\nhttps.createServer(options, function (req, res) {\n  var rc = 200;\n  var parsed = httpSignature.parseRequest(req);\n  var pub = fs.readFileSync(parsed.keyId, \'ascii\');\n  if (!httpSignature.verifySignature(parsed, pub))\n    rc = 401;\n\n  res.writeHead(rc);\n  res.end();\n}).listen(8443);\n`\n\n## Installation\n\n    npm install http-signature\n\n## License\n\nMIT.\n\n## Bugs\n\nSee https://github.com/joyent/node-http-signature/issues.\n',
1037 silly resolved     readmeFilename: 'README.md',
1037 silly resolved     _id: 'http-signature@0.10.1',
1037 silly resolved     _from: 'http-signature@~0.10.0' },
1037 silly resolved   { author: { name: 'GoInstant Inc., a salesforce.com company' },
1037 silly resolved     license: 'MIT',
1037 silly resolved     name: 'tough-cookie',
1037 silly resolved     description: 'RFC6265 Cookies and Cookie Jar for node.js',

## 1037 silly resolved     keywords:

1641 silly lockFile 89ddb20e-ttp-signature-0-10-1-package-tgz /home/ubuntu/.npm/http-signature/0.10.1/package.tgz
1642 silly lockFile 89ddb20e-ttp-signature-0-10-1-package-tgz /home/ubuntu/.npm/http-signature/0.10.1/package.tgz
1643 verbose read json /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/form-data/node_modules/mime-types/package.json
1644 silly gunzTarPerm extractEntry test/integration/test-delayed-stream-pause.js
1645 silly gunzTarPerm extractEntry test/integration/test-delayed-stream.js
1646 info preinstall http-signature@0.10.1
1647 verbose from cache /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/http-signature/package.json
1648 verbose readDependencies using package.json deps
1649 verbose from cache /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/http-signature/package.json
1650 verbose readDependencies using package.json deps
1651 verbose cache add [ 'assert-plus@^0.1.5', null ]
1652 verbose cache add name=undefined spec="assert-plus@^0.1.5" args=["assert-plus@^0.1.5",null]
1653 verbose parsed url { protocol: null,
1653 verbose parsed url   slashes: null,
1653 verbose parsed url   auth: null,
1653 verbose parsed url   host: null,
1653 verbose parsed url   port: null,
1653 verbose parsed url   hostname: null,
1653 verbose parsed url   hash: null,
1653 verbose parsed url   search: null,
1653 verbose parsed url   query: null,
1653 verbose parsed url   pathname: 'assert-plus@^0.1.5',
1653 verbose parsed url   path: 'assert-plus@^0.1.5',
1653 verbose parsed url   href: 'assert-plus@^0.1.5' }
1654 verbose cache add name="assert-plus" spec="^0.1.5" args=["assert-plus","^0.1.5"]
1655 verbose parsed url { protocol: null,
1655 verbose parsed url   slashes: null,
1655 verbose parsed url   auth: null,
1655 verbose parsed url   host: null,
1655 verbose parsed url   port: null,
1655 verbose parsed url   hostname: null,
1655 verbose parsed url   hash: null,
1655 verbose parsed url   search: null,
1655 verbose parsed url   query: null,
1655 verbose parsed url   pathname: '^0.1.5',
1655 verbose parsed url   path: '^0.1.5',
1655 verbose parsed url   href: '^0.1.5' }
1656 verbose addNamed [ 'assert-plus', '^0.1.5' ]
1657 verbose addNamed [ null, null ]
1658 silly lockFile 0f85a4cc-assert-plus-0-1-5 assert-plus@^0.1.5
1659 verbose lock assert-plus@^0.1.5 /home/ubuntu/.npm/0f85a4cc-assert-plus-0-1-5.lock
1660 verbose cache add [ 'asn1@0.1.11', null ]
1661 verbose cache add name=undefined spec="asn1@0.1.11" args=["asn1@0.1.11",null]
1662 verbose parsed url { protocol: null,
1662 verbose parsed url   slashes: null,
1662 verbose parsed url   auth: null,
1662 verbose parsed url   host: null,
1662 verbose parsed url   port: null,
1662 verbose parsed url   hostname: null,
1662 verbose parsed url   hash: null,

## 1662 verbose parsed url   search: null,

1664 verbose parsed url   query: null,
1664 verbose parsed url   pathname: '0.1.11',
1664 verbose parsed url   path: '0.1.11',
1664 verbose parsed url   href: '0.1.11' }
1665 verbose addNamed [ 'asn1', '0.1.11' ]
1666 verbose addNamed [ '0.1.11', '0.1.11' ]
1667 silly lockFile 41ecb821-asn1-0-1-11 asn1@0.1.11
1668 verbose lock asn1@0.1.11 /home/ubuntu/.npm/41ecb821-asn1-0-1-11.lock
1669 silly lockFile c778c6dd-orm-data-node-modules-mime-types /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/form-data/node_modules/mime-types
1670 silly lockFile c778c6dd-orm-data-node-modules-mime-types /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/form-data/node_modules/mime-types
1671 info addNameTag [ 'assert-plus', '^0.1.5' ]
1672 verbose cache add [ 'ctype@0.5.3', null ]
1673 verbose cache add name=undefined spec="ctype@0.5.3" args=["ctype@0.5.3",null]
1674 verbose parsed url { protocol: null,
1674 verbose parsed url   slashes: null,
1674 verbose parsed url   auth: null,
1674 verbose parsed url   host: null,
1674 verbose parsed url   port: null,
1674 verbose parsed url   hostname: null,
1674 verbose parsed url   hash: null,

## 1674 verbose parsed url   search: null,

1676 verbose parsed url   path: '0.5.3',
1676 verbose parsed url   href: '0.5.3' }
1677 verbose addNamed [ 'ctype', '0.5.3' ]
1678 verbose addNamed [ '0.5.3', '0.5.3' ]
1679 silly lockFile d3ce18c2-ctype-0-5-3 ctype@0.5.3
1680 verbose lock ctype@0.5.3 /home/ubuntu/.npm/d3ce18c2-ctype-0-5-3.lock
1681 silly lockFile 0f69d6d6-npm-mime-types-2-0-7-package-tgz /home/ubuntu/.npm/mime-types/2.0.7/package.tgz
1682 silly lockFile 0f69d6d6-npm-mime-types-2-0-7-package-tgz /home/ubuntu/.npm/mime-types/2.0.7/package.tgz
1683 silly gunzTarPerm extractEntry test/integration/test-handle-source-errors.js
1684 silly gunzTarPerm extractEntry test/integration/test-max-data-size.js
1685 verbose url raw assert-plus
1686 verbose url resolving [ 'https://registry.npmjs.org/', './assert-plus' ]
1687 verbose url resolved https://registry.npmjs.org/assert-plus
1688 info trying registry request attempt 1 at 15:09:47
1689 verbose etag "9K8FV2TOI8XZL5FGTU5WW1A5R"
1690 http GET https://registry.npmjs.org/assert-plus
1691 verbose url raw asn1/0.1.11
1692 verbose url resolving [ 'https://registry.npmjs.org/', './asn1/0.1.11' ]
1693 verbose url resolved https://registry.npmjs.org/asn1/0.1.11
1694 info trying registry request attempt 1 at 15:09:47
1695 verbose etag "6C3UZVSME8HO9P85EMANR90TC"
1696 http GET https://registry.npmjs.org/asn1/0.1.11
1697 verbose read json /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/node-uuid/package.json
1698 verbose url raw ctype/0.5.3
1699 verbose url resolving [ 'https://registry.npmjs.org/', './ctype/0.5.3' ]

## 1700 verbose url resolved https://registry.npmjs.org/ctype/0.5.3

1722 silly addNameRange     '1.0.32',
1722 silly addNameRange     '1.0.32-1',
1722 silly addNameRange     '1.0.33-1',
1722 silly addNameRange     '1.0.33-2',
1722 silly addNameRange     '1.0.33' ] ]
1723 verbose addNamed [ 'readable-stream', '1.0.33' ]
1724 verbose addNamed [ '1.0.33', '1.0.33' ]
1725 silly lockFile f026aa23-readable-stream-1-0-33 readable-stream@1.0.33
1726 verbose lock readable-stream@1.0.33 /home/ubuntu/.npm/f026aa23-readable-stream-1-0-33.lock
1727 silly addNameRange { name: 'mime-db', range: '>=1.5.0- <1.6.0-', hasData: false }
1728 http 304 https://registry.npmjs.org/assert-plus
1729 silly registry.get cb [ 304,
1729 silly registry.get   { date: 'Wed, 21 Jan 2015 15:07:40 GMT',
1729 silly registry.get     server: 'Apache',
1729 silly registry.get     via: '1.1 varnish',
1729 silly registry.get     'last-modified': 'Wed, 21 Jan 2015 15:07:40 GMT',
1729 silly registry.get     'cache-control': 'max-age=60',
1729 silly registry.get     etag: '"9K8FV2TOI8XZL5FGTU5WW1A5R"',
1729 silly registry.get     age: '25',
1729 silly registry.get     'x-served-by': 'cache-iad2129-IAD',
1729 silly registry.get     'x-cache': 'HIT',
1729 silly registry.get     'x-cache-hits': '1',
1729 silly registry.get     'x-timer': 'S1421852860.803323,VS0,VE0',
1729 silly registry.get     vary: 'Accept',
1729 silly registry.get     'content-length': '0',
1729 silly registry.get     'keep-alive': 'timeout=10, max=50',
1729 silly registry.get     connection: 'Keep-Alive' } ]
1730 verbose etag assert-plus from cache
1731 silly gunzTarPerm extractEntry test/integration/test-pipe-resumes.js
1732 silly gunzTarPerm extractEntry test/integration/test-proxy-readable.js
1733 verbose read json /home/ubuntu/.npm/readable-stream/1.0.33/package/package.json
1734 silly lockFile ce1936d8-s-request-node-modules-node-uuid /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/node-uuid
1735 silly lockFile ce1936d8-s-request-node-modules-node-uuid /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/node-uuid
1736 http 304 https://registry.npmjs.org/asn1/0.1.11
1737 silly registry.get cb [ 304,
1737 silly registry.get   { date: 'Wed, 21 Jan 2015 15:07:40 GMT',
1737 silly registry.get     server: 'Apache',

## 1737 silly registry.get     via: '1.1 varnish',

1737 silly registry.get     connection: 'Keep-Alive' } ]
1738 verbose etag asn1/0.1.11 from cache
1739 silly lockFile cf92c8a7--npm-node-uuid-1-4-2-package-tgz /home/ubuntu/.npm/node-uuid/1.4.2/package.tgz
1740 silly lockFile cf92c8a7--npm-node-uuid-1-4-2-package-tgz /home/ubuntu/.npm/node-uuid/1.4.2/package.tgz
1741 verbose url raw mime-db
1742 verbose url resolving [ 'https://registry.npmjs.org/', './mime-db' ]
1743 verbose url resolved https://registry.npmjs.org/mime-db
1744 info trying registry request attempt 1 at 15:09:47
1745 verbose etag "8595AUNKM174ZM0AJHIV11A9A"
1746 http GET https://registry.npmjs.org/mime-db
1747 silly lockFile 0f85a4cc-assert-plus-0-1-5 assert-plus@^0.1.5
1748 silly lockFile 0f85a4cc-assert-plus-0-1-5 assert-plus@^0.1.5
1749 verbose about to build /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/http-signature
1750 info /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/http-signature unbuild
1751 verbose from cache /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/http-signature/package.json
1752 info preuninstall http-signature@0.10.1
1753 info preinstall node-uuid@1.4.2
1754 info uninstall http-signature@0.10.1
1755 verbose read json /home/ubuntu/.npm/asn1/0.1.11/package/package.json
1756 verbose from cache /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/node-uuid/package.json
1757 verbose read json /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/qs/package.json
1758 silly lockFile f026aa23-readable-stream-1-0-33 readable-stream@1.0.33
ubuntu@i-0134faed:~/etherpad-lite$ grep -B10 assert-plus ./src/npm-debug.log 
1037 silly resolved     contributors: [ [Object], [Object] ],
1037 silly resolved     repository:
1037 silly resolved      { type: 'git',
1037 silly resolved        url: 'git://github.com/joyent/node-http-signature.git' },
1037 silly resolved     homepage: 'https://github.com/joyent/node-http-signature/',
1037 silly resolved     bugs: 'https://github.com/joyent/node-http-signature/issues',
1037 silly resolved     keywords: [ 'https', 'request' ],
1037 silly resolved     engines: { node: '>=0.8' },
1037 silly resolved     main: 'lib/index.js',
1037 silly resolved     scripts: { test: 'tap test/*.js' },

## 1037 silly resolved     dependencies: { 'assert-plus': '^0.1.5', asn1: '0.1.11', ctype: '0.5.3' },

1641 silly lockFile 89ddb20e-ttp-signature-0-10-1-package-tgz /home/ubuntu/.npm/http-signature/0.10.1/package.tgz
1642 silly lockFile 89ddb20e-ttp-signature-0-10-1-package-tgz /home/ubuntu/.npm/http-signature/0.10.1/package.tgz
1643 verbose read json /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/form-data/node_modules/mime-types/package.json
1644 silly gunzTarPerm extractEntry test/integration/test-delayed-stream-pause.js
1645 silly gunzTarPerm extractEntry test/integration/test-delayed-stream.js
1646 info preinstall http-signature@0.10.1
1647 verbose from cache /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/http-signature/package.json
1648 verbose readDependencies using package.json deps
1649 verbose from cache /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/http-signature/package.json
1650 verbose readDependencies using package.json deps
1651 verbose cache add [ 'assert-plus@^0.1.5', null ]
1652 verbose cache add name=undefined spec="assert-plus@^0.1.5" args=["assert-plus@^0.1.5",null]
1653 verbose parsed url { protocol: null,
1653 verbose parsed url   slashes: null,
1653 verbose parsed url   auth: null,
1653 verbose parsed url   host: null,
1653 verbose parsed url   port: null,
1653 verbose parsed url   hostname: null,
1653 verbose parsed url   hash: null,
1653 verbose parsed url   search: null,
1653 verbose parsed url   query: null,
1653 verbose parsed url   pathname: 'assert-plus@^0.1.5',
1653 verbose parsed url   path: 'assert-plus@^0.1.5',
1653 verbose parsed url   href: 'assert-plus@^0.1.5' }

## 1654 verbose cache add name="assert-plus" spec="^0.1.5" args=["assert-plus","^0.1.5"]

1655 verbose parsed url   auth: null,
1655 verbose parsed url   host: null,
1655 verbose parsed url   port: null,
1655 verbose parsed url   hostname: null,
1655 verbose parsed url   hash: null,
1655 verbose parsed url   search: null,
1655 verbose parsed url   query: null,
1655 verbose parsed url   pathname: '^0.1.5',
1655 verbose parsed url   path: '^0.1.5',
1655 verbose parsed url   href: '^0.1.5' }
1656 verbose addNamed [ 'assert-plus', '^0.1.5' ]
1657 verbose addNamed [ null, null ]
1658 silly lockFile 0f85a4cc-assert-plus-0-1-5 assert-plus@^0.1.5

## 1659 verbose lock assert-plus@^0.1.5 /home/ubuntu/.npm/0f85a4cc-assert-plus-0-1-5.lock

1664 verbose parsed url   query: null,
1664 verbose parsed url   pathname: '0.1.11',
1664 verbose parsed url   path: '0.1.11',
1664 verbose parsed url   href: '0.1.11' }
1665 verbose addNamed [ 'asn1', '0.1.11' ]
1666 verbose addNamed [ '0.1.11', '0.1.11' ]
1667 silly lockFile 41ecb821-asn1-0-1-11 asn1@0.1.11
1668 verbose lock asn1@0.1.11 /home/ubuntu/.npm/41ecb821-asn1-0-1-11.lock
1669 silly lockFile c778c6dd-orm-data-node-modules-mime-types /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/form-data/node_modules/mime-types
1670 silly lockFile c778c6dd-orm-data-node-modules-mime-types /home/ubuntu/etherpad-lite/src/node_modules/request/node_modules/form-data/node_modules/mime-types

## 1671 info addNameTag [ 'assert-plus', '^0.1.5' ]

1676 verbose parsed url   path: '0.5.3',
1676 verbose parsed url   href: '0.5.3' }
1677 verbose addNamed [ 'ctype', '0.5.3' ]
1678 verbose addNamed [ '0.5.3', '0.5.3' ]
1679 silly lockFile d3ce18c2-ctype-0-5-3 ctype@0.5.3
1680 verbose lock ctype@0.5.3 /home/ubuntu/.npm/d3ce18c2-ctype-0-5-3.lock
1681 silly lockFile 0f69d6d6-npm-mime-types-2-0-7-package-tgz /home/ubuntu/.npm/mime-types/2.0.7/package.tgz
1682 silly lockFile 0f69d6d6-npm-mime-types-2-0-7-package-tgz /home/ubuntu/.npm/mime-types/2.0.7/package.tgz
1683 silly gunzTarPerm extractEntry test/integration/test-handle-source-errors.js
1684 silly gunzTarPerm extractEntry test/integration/test-max-data-size.js
1685 verbose url raw assert-plus
1686 verbose url resolving [ 'https://registry.npmjs.org/', './assert-plus' ]
1687 verbose url resolved https://registry.npmjs.org/assert-plus
1688 info trying registry request attempt 1 at 15:09:47
1689 verbose etag "9K8FV2TOI8XZL5FGTU5WW1A5R"

## 1690 http GET https://registry.npmjs.org/assert-plus

1722 silly addNameRange     '1.0.32',
1722 silly addNameRange     '1.0.32-1',
1722 silly addNameRange     '1.0.33-1',
1722 silly addNameRange     '1.0.33-2',
1722 silly addNameRange     '1.0.33' ] ]
1723 verbose addNamed [ 'readable-stream', '1.0.33' ]
1724 verbose addNamed [ '1.0.33', '1.0.33' ]
1725 silly lockFile f026aa23-readable-stream-1-0-33 readable-stream@1.0.33
1726 verbose lock readable-stream@1.0.33 /home/ubuntu/.npm/f026aa23-readable-stream-1-0-33.lock
1727 silly addNameRange { name: 'mime-db', range: '>=1.5.0- <1.6.0-', hasData: false }

## 1728 http 304 https://registry.npmjs.org/assert-plus

1729 silly registry.get     etag: '"9K8FV2TOI8XZL5FGTU5WW1A5R"',
1729 silly registry.get     age: '25',
1729 silly registry.get     'x-served-by': 'cache-iad2129-IAD',
1729 silly registry.get     'x-cache': 'HIT',
1729 silly registry.get     'x-cache-hits': '1',
1729 silly registry.get     'x-timer': 'S1421852860.803323,VS0,VE0',
1729 silly registry.get     vary: 'Accept',
1729 silly registry.get     'content-length': '0',
1729 silly registry.get     'keep-alive': 'timeout=10, max=50',
1729 silly registry.get     connection: 'Keep-Alive' } ]

## 1730 verbose etag assert-plus from cache

1737 silly registry.get     connection: 'Keep-Alive' } ]
1738 verbose etag asn1/0.1.11 from cache
1739 silly lockFile cf92c8a7--npm-node-uuid-1-4-2-package-tgz /home/ubuntu/.npm/node-uuid/1.4.2/package.tgz
1740 silly lockFile cf92c8a7--npm-node-uuid-1-4-2-package-tgz /home/ubuntu/.npm/node-uuid/1.4.2/package.tgz
1741 verbose url raw mime-db
1742 verbose url resolving [ 'https://registry.npmjs.org/', './mime-db' ]
1743 verbose url resolved https://registry.npmjs.org/mime-db
1744 info trying registry request attempt 1 at 15:09:47
1745 verbose etag "8595AUNKM174ZM0AJHIV11A9A"
1746 http GET https://registry.npmjs.org/mime-db
1747 silly lockFile 0f85a4cc-assert-plus-0-1-5 assert-plus@^0.1.5
1748 silly lockFile 0f85a4cc-assert-plus-0-1-5 assert-plus@^0.1.5

**Comment by jdotpz** [comment]
Here's a readable version of an attempt to npm install in src

http://pastebin.mozilla.org/8275154

**Comment by JohnMcLear** [comment]
Please provide exact steps to replicate.

**Comment by JohnMcLear** [comment]
I have a feeling your version of npm is old and can't handle ^..  Please try install latest nodejs and see if the problem persists.

**Comment by jdotpz** [comment]
Roger that, will do right now.  That may well be the case.  Which specific
version are you using?

**Comment by JohnMcLear** [comment]
I use nvm which means I hot switch between versions..  So depends on the moon really..

```
jose@PBOH-SNUG:~/etherpad-lite/src/static/js$ nvm ls
     v0.10.4
    v0.11.14
->    system
latest -> 0.11.14 (-> v0.11.14)
```

currently I'm using 11.14

**Comment by jdotpz** [comment]
Yup. using 0.11.15 did the trick.  I was using latest from stable, 0.10.33 or so.

I'll see if I can't get this rolled up into a deb.  My builder box I usually use won't work, since the versioning on node is diff, but I can do some dark magic on this box and just build it from here.

**Comment by JohnMcLear** [comment]
Coolies :) I literally was pondering doing this a few days ago so getting this level of help is greatly appreciated!  Pretty excited about the possibilities of `apt-get install etherpad` in the near future!  If there is anything we can do as a foundation to make things official just let me know

**Comment by OpenMatt** [comment]
how did this one work out @jdotpz ?

**Comment by jdotpz** [comment]
Quite well @OpenMatt 
I have the latest and greatest version running, and will eventually get a .deb rolled (after this heartbeat).
