### ISSUE TITLE
Update default pad text

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-lightsaber#10]
Change default text:change default text to communicate all the new features available to MoFos. Maybe point them to a blog post explaining all of what's new and improved

**Comment by JohnMcLear** [comment]
See settings.json

**Comment by OpenMatt** [comment]
I'll take this one. And write the updated text once we have updates to let people know about.

**Comment by OpenMatt** [comment]
to make this change: pad.webmaker.org/admin
@jdotpz : let me know the URL once it changes

**Comment by OpenMatt** [comment]
@jdotpz I went to update this copy just now, but it looks like  pad.webmaker.org/admin is no longer the right admin URL?

**Comment by OpenMatt** [comment]
@jdotpz let's go with this:

**Etherpad is new and improved!**
Copy and paste images, add comments, embed pads, and more!
More details here: http://pad.webmaker.org/new

**Comment by jdotpz** [comment]
I've scheduled pad.webmaker.org to recycle at 10pm ET and update this text.

**Comment by OpenMatt** [comment]
done!
