### ISSUE TITLE
Enable export to HTML

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-lightsaber#11]
This is extremely handy for easily turning etherpads into blog posts, etc.

**Comment by JohnMcLear** [comment]
It's enabled by default

**Comment by OpenMatt** [comment]
I tried it on pad.webmaker.org and couldn't get it to export actual HTML -- it just resulted in a blank export. Would test it but pad.webmaker.org is down right now.

**Comment by JohnMcLear** [comment]
https://beta.etherpad.org is a useful playground for life.

**Comment by jdotpz** [comment]
Perhaps we need to be on the develop branch for it.  I'm going to roll a .deb for it today and get it over to etherpadorg as well as use it to install all sorts of properly on our demo instance.

**Comment by jdotpz** [comment]
Seems to be working on the new branch!
![htmlbaby](https://cloud.githubusercontent.com/assets/1373628/5942316/5938aabe-a6dc-11e4-8587-5cc75ed73454.gif)

**Comment by OpenMatt** [comment]
just tried this and it doesn't seem to work

**Comment by OpenMatt** [comment]
I'm going to make this a P1 because, with the new formatting features, this could save program managers a lot of time. It means we can turn an etherpad agenda into a blog post much more quickly, preserving formatting, etc.

**Comment by JohnMcLear** [comment]
I just tested it and it's working for me...

What problem are you having @OpenMatt  ?

https://pad.webmaker.org/p/FgOLLbBJuS/export/html

**Comment by jdotpz** [comment]
Yup, it works under /p but not under the reverse proxy.  I'll double check my reverse proxying.

**Comment by jdotpz** [comment]
Hmmm...this is my reverse proxy, but i'm not so sure what I'm supposed to add there?  apologies!
http://pastebin.mozilla.org/8525136

**Comment by JohnMcLear** [comment]
@jdotpz I don't know what URL endpoints you expect to work so I'm not sure how useful I am?  Like how are you getting the wrong URLs for exporting?  They should be like..   https://pad.webmaker.org/p/FgOLLbBJuS/export/html

If you are doing..

https://pad.webmaker.org/FgOLLbBJuS/export/html

Then you will need to rewrite that to

https://pad.webmaker.org/p/FgOLLbBJuS/export/html

I haven't written nginx in a while but I guess it would be something similar to

`rewrite ^(.*)/export/(.*) /p/$1/export/$2 break;`

Prior to the `rewrite /(.*) /p/$1;` rule..  

Again disclaimer I haven't tested this that's just what I assume is needed from looking at your nginx config..

**Comment by jdotpz** [comment]
Nah, afraid that didn't do the trick.  I suck at rewrites, and haven't had time to mess with it after testing.

**Comment by JohnMcLear** [comment]
Weirdly I tested this like 5 mins ago and your rule is working..

**Comment by JohnMcLear** [comment]
https://pad.webmaker.org/FgOLLbBJuS/export/html is an active endpoint now...  What am I missing?

**Comment by jdotpz** [comment]
It seems the plugin itself is pointing to a null link:

![screen shot 2015-02-10 at 2 11 25 pm](https://cloud.githubusercontent.com/assets/1373628/6135499/c6aba66c-b12e-11e4-8906-36626926c5de.JPG)

**Comment by jdotpz** [comment]
![eth-null](https://cloud.githubusercontent.com/assets/1373628/6135518/f6892666-b12e-11e4-8f4f-057226ed315e.gif)

**Comment by JohnMcLear** [comment]
How do you see that?  under export on the pad?
----- Reply message -----

**Comment by jdotpz** [comment]
(Note the url of the links I'm highlighting in my lower left corner of the browser)

**Comment by jdotpz** [comment]
Correct, under export as shown in that gif.

**Comment by JohnMcLear** [comment]
Aha I see this now..

**Comment by JohnMcLear** [comment]
I put a fix into develop, give it a go

https://github.com/ether/etherpad-lite/pull/2515

**Comment by OpenMatt** [comment]
Thanks @JohnMcLear !

**Comment by OpenMatt** [comment]
done! this now works.
