### ISSUE TITLE
Enable export to PDF

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-lightsaber#12]
Also useful for publishing. This used to exist -- not sure if it still does.

**Comment by JohnMcLear** [comment]
It still does exist, you just need to install abiword and set the path in settings.json

**Comment by jdotpz** [comment]
![screen shot 2015-01-28 at 10 19 10 am](https://cloud.githubusercontent.com/assets/1373628/5941518/211d431a-a6d7-11e4-8fe4-2f3baaa3b21b.JPG)

**Comment by OpenMatt** [comment]
I just tried this and it doesn't appear to work

**Comment by JohnMcLear** [comment]
What problem are you seeing?  https://pad.webmaker.org/p/kljsdlfjskldjf/export/pdf works for me

**Comment by jdotpz** [comment]
Hmm, that works for me too, odd!

Ah, I see...if its done from the /p/padname path, it works fine, if done from the /padname path it does not.

**Comment by JohnMcLear** [comment]
Again please see the rewrite rules we provide in the wiki!

**Comment by jdotpz** [comment]
Heh, these _were_ from the wiki. :)

**Comment by JohnMcLear** [comment]
Hrm must have missed the export rewrite rules somehow?  If they are not there please fix em up :)
----- Reply message -----

**Comment by JohnMcLear** [comment]
Was it 

```
        rewrite ^/(.*)/export/(.*) /p/$1/export/$2 break;
```

That fixed this?  Please paste your rule :)

**Comment by OpenMatt** [comment]
just tested --can confirm this now works.
