### ISSUE TITLE
Set up wiki.webmaker.org on staging

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-lightsaber#13]
GOAL: spin up our own wiki instance that allows us to do things the mozilla wiki is currently unable to. Like: embed lists of Git Hub tickets, embed etherpads directly through iframes, etc. 

requirements:

P1
- can embed lists of GitHub issues 
- can embed lists of Bugzilla tickets (e.g., https://wiki.mozilla.org/Webmaker )
- embeds iframes 

P2
- supports markdown
- fast
- mobile-friendly
- pretty themes

Recommendation: use MediaWiki. Looks like it will do all  the P1s. Plus has a plugin to support markdown.

**Comment by OpenMatt** [comment]
Some potentially useful documentation:

https://wiki.mozilla.org/Bugzilla:REST_API
Sprinter http://bugzilla-sprinter.herokuapp.com  (built by @k88hudson )
http://www.mediawikiwidgets.org/Iframe
https://github.com/aaronpk/MediaWiki-Github-Issues
http://www.mediawiki.org/wiki/Extension:MarkdownSyntax

**Comment by OpenMatt** [comment]
Wiki Matrix comparison, in case we don't like MediaWiki: http://mzl.la/1sWwf4D

**Comment by OpenMatt** [comment]
- Talked with Christie K about this -- we can use this wiki install as a chance to learn some stuff that we can contribute back into the Mozilla Wiki project. As per their roadmap: 
  https://wiki.mozilla.org/MozillaWiki:Roadmap

**Comment by JohnMcLear** [comment]
It makes a lot of sense to just use Etherpad as an editor within Mediawiki.  Mediawiki afaik offers that.  @MarkTraceur from #etherpad-lite-dev freenode.net is afaik leading on it.  He is based in SF for Wikimedia.  I will bump him with this thread.

**Comment by OpenMatt** [comment]
@JohnMcLear : you mean embedding an Etherpad in a MediaWiki page through an iFrame?

**Comment by JohnMcLear** [comment]
I'm not actually sure how/what they are doing but it's worth getting in touch w/ him

**Comment by MarkTraceur** [comment]
@JohnMcLear I'm actually in Minnesota now, but I'd be happy to help a bit.

EtherEditor exists - it hooks into the MediaWiki editing interface and lets you edit pages collaboratively. The Etherpad extension embeds a pad into a page, which is fine, but has less integration with MediaWiki.

**Comment by MarkTraceur** [comment]
Fair warning: EtherEditor is probably broken, I think it's using some deprecated hooks or API calls for EPL.

**Comment by GPHemsley** [comment]
Hey, MozillaWiki module peer here.

I don't think spinning up your own wiki instance is going to be particularly beneficial to you, us, or anyone else in the long run, and I'm curious as to why you think it is the right course of action.

What usecases are you trying to accommodate, and why did you not approach us first?

I really think it would be better for us to work together rather than in parallel.

**Comment by OpenMatt** [comment]
Hi Gordon! Christie K and I talked about it via email. We want to spin up our own instance so that we can experiment and break things. If we land on something good, we'll contribute it back in.

**Comment by OpenMatt** [comment]
@jdotpz : how's this one going?

**Comment by jdotpz** [comment]
Poorly thus far @OpenMatt .
I have spun up a few instances that were bunk.  I'm cooking on the etherpad stuff, then will move to mediawiki.

**Comment by OpenMatt** [comment]
Sounds good. Prioritizing etherpad over mediawiki makes sense.

**Comment by jdotpz** [comment]
http://ec2-54-158-171-148.compute-1.amazonaws.com/index.php/?title=Main_Page is the demo server I'm working on.

Here were my installer info's

vhost:
http://pastebin.mozilla.org/8426027

Installed in /var/www/html
php ./maintenance/install.php --dbuser dbuser --dbpass dbpass --dbserver localhost --dbtype mysql --dbname mediawiki --pass mainpw --scriptpath / WebmakerWiki mofoadmin

**Comment by jdotpz** [comment]
http://wiki-staging-432326455.us-east-1.elb.amazonaws.com/index.php/?title=Main_Page
It's failing quite a bit, even as I added --server https://wiki.mofostaging.net argument to the install.

![gah-wiki](https://cloud.githubusercontent.com/assets/1373628/5966816/2b4988fc-a7cd-11e4-9988-6e1ebf3f2eaa.gif)

**Comment by jdotpz** [comment]
OK, fixed that issue!  

Their wiki lies!  It's hard deploying liar software.
*
The URL base path to the directory containing the wiki;
defaults for all runtime URL paths are based off of this.
For more information on customizing the URLs
(like /w/index.php/Page_title to /wiki/Page_title) please see:
https://www.mediawiki.org/wiki/Manual:Short_URL*
$wgScriptPath = "https://wiki.mofostaging.net";
This change fixes us up proper.

**Comment by OpenMatt** [comment]
@ nice! @jdotpz any next steps here? Or can we close this one?

**Comment by jdotpz** [comment]
Definitely next steps, leave it open

**Comment by OpenMatt** [comment]
Goal is to be able to embed:
a) etherpad (through an iframe)
b) Git Hub issues, and 
c) Bugzilla tickets
in a single wiki page

**Comment by OpenMatt** [comment]
- Lots of great progress on the main Mozilla MediaWiki happening here: https://wiki.mozilla.org/MozillaWiki:News/2015-01/Mediawiki_upgrade,_new_deployment_model_and_Widgets
- So I've asked about Git Hub issue support again here https://bugzilla.mozilla.org/show_bug.cgi?id=1017714

**Comment by OpenMatt** [comment]
wiki.mofostaging.net is now up and running

**Comment by OpenMatt** [comment]
@jdotpz should we mark this one resolved?

**Comment by jdotpz** [comment]
Sure thing, we'll get to new issues for specific features we want to try.
