### ISSUE TITLE
Enable commenting in etherpad

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-lightsaber#15]
This is an extremely useful Google Docs feature. Replicating it in Etherpad would be useful. 

plug-ins: 

```
ep_comments_page Comments on the right side of the page.

ep_feedback_ii Add a feedback button for idea informer to the right hand toolbar
```

**Comment by jdotpz** [comment]
Comments seem to be working!
![comments-eth](https://cloud.githubusercontent.com/assets/1373628/5942239/e895d66a-a6db-11e4-9c6f-4f748eaa38ae.gif)

**Comment by OpenMatt** [comment]
Nice! Lets mark this one resolved! :)
