### ISSUE TITLE
Add linkifying

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-lightsaber#16]
Real links!

plugins:

```
ep_linkify Adds internal links to etherpad lite. To create internal links use example style formatting
```

**Comment by jdotpz** [comment]
![screen shot 2015-01-28 at 10 13 56 am](https://cloud.githubusercontent.com/assets/1373628/5941390/65364444-a6d6-11e4-8997-bebd6faee9ba.JPG)

**Comment by OpenMatt** [comment]
@jdotpz we uninstalled this because it was causing stability issues, correct?
(if so: that's fine. lets wontfix this one. just curious.)
