### ISSUE TITLE
Link to a line number or anchor

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-lightsaber#17]
```
Link to anchor
```

e.g,

```
ep_scrollto Scroll to a specific line number based on a parameter of lineNumber in the URL IE http://test.com/p/foo#lineNumber=

ep_scrolltoanchor Scroll to line containing #anchor based on a parameter of anchor in the URL, e.g. http://test.com/p/foo#anchor=Cool
```

**Comment by jdotpz** [comment]
I have installed ep_scrollto and tested it.  It seems nice, but we've been having difficulty with items saving.  I'm working on resolving that, so I'll leave this open.

**Comment by jdotpz** [comment]
![linelinks-eth](https://cloud.githubusercontent.com/assets/1373628/5946549/38515006-a6fc-11e4-9076-821fb3eb4af8.gif)

**Comment by OpenMatt** [comment]
So the way this works is: add "#lineNumber=5" to any etherpad link

**Comment by jdotpz** [comment]
I've reopened because I've removed the linkify plugin while working to stabilize the instance.

**Comment by OpenMatt** [comment]
I'd suggest we wontfix this one -- I'm not sure it's that useful.
