### ISSUE TITLE
Fix "style" drop down 

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-lightsaber#2]
Ensure formatting works (H1, H2, etc.)

An example of what we mean http://workopen.org/github_howto

**Comment by JohnMcLear** [comment]
Use ep_headings2

**Comment by OpenMatt** [comment]
@JohnMcLear Thanks for your help with this John! One thing I'm not clear on is: what does ep_headings2 provides that Etherpad 1.5 doesn't out of the box? 

Here, for example, I have options for H1, H2, H3 etc built in: 
http://workopen.org/github_howto

**Comment by JohnMcLear** [comment]
Peep the ep_headings2 readme.  It basically stops it from being shit.

**Comment by OpenMatt** [comment]
nice. @jdotpz : let's install this one.

**Comment by jdotpz** [comment]
Hmmm, I'm not seeing it in the list.  Is it just available on npm?
![screen shot 2015-01-28 at 11 12 57 am](https://cloud.githubusercontent.com/assets/1373628/5942680/aba67810-a6de-11e4-9cac-350d3e33c193.JPG)

**Comment by JohnMcLear** [comment]
```
jose@PBOH-SNUG:~$ npm install ep_headings2
npm WARN package.json felix-couchdb@1.0.7 No repository field.
npm WARN package.json ep_br_to_p@0.0.2 No repository field.
npm WARN package.json ep_cursortrace@2.0.9 No repository field.
npm WARN package.json ep_invite_via_email@0.0.4 No README data
npm WARN package.json ep_special_characters@0.0.6 No repository field.
npm WARN package.json ep_special_characters@0.0.6 No README data
npm WARN package.json ep_subscript@0.0.6 No repository field.
npm WARN package.json ep_superscript@0.0.3 No repository field.
ep_headings2@0.0.8 node_modules/ep_headings2
jose@PBOH-SNUG:~$ 
```

weird it's available on npm

**Comment by JohnMcLear** [comment]
heh I don't see it on beta.etherpad.org either..  Feck.  Fixing

**Comment by jdotpz** [comment]
ubuntu@i-0134faed:/opt/etherpad/src$ npm install ep_headings2
npm WARN package.json async-stacktrace@0.0.2 No repository field.
npm WARN package.json channels@0.0.4 No repository field.
npm WARN package.json tinycon@0.0.1 No repository field.

Installed and bounced services.  Let's see how she does.

**Comment by JohnMcLear** [comment]
Oh I'm being an idiot I already had it installed no wonder I couldn't see it..  Yea make sure you are running latest develop it should be there..

**Comment by jdotpz** [comment]
It's there!
