### ISSUE TITLE
Install Git Hub extension for wiki

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-lightsaber#24]

**Comment by OpenMatt** [comment]
We can review this in our stand-up Tues

**Comment by OpenMatt** [comment]
Here's the extension that I believe David would like to use: https://github.com/aaronpk/MediaWiki-Github-Issues

**Comment by OpenMatt** [comment]
Plus useful context in this bugzilla thread: https://bugzilla.mozilla.org/show_bug.cgi?id=1017714#c9

**Comment by jdotpz** [comment]
All setup:  http://wiki.mofostaging.net/Main_Page has an example from the github repo.

**Comment by OpenMatt** [comment]
This appears to be working here: http://wiki.mofostaging.net/Github_test

**Comment by OpenMatt** [comment]
It would be great to just display the title, without the description and number of comments. I emailed the author, Aaron, to see if that's possible.

**Comment by OpenMatt** [comment]
From Aaron: 
"I don't have a way to customize that from within the wiki, but it shouldn't be too hard to add as an option to the plugin. If you do want to edit that, feel free to send me a pull request!"

**Comment by OpenMatt** [comment]
this one's done
