### ISSUE TITLE
Install iFrame extension for wiki

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-lightsaber#26]
So that we can embed etherpads directly. Like this:
http://openmatt.org/embed-your-etherpads/

**Comment by OpenMatt** [comment]
@jdotpz we can check in on the P1s Tues in our stand-up

**Comment by OpenMatt** [comment]
http://www.mediawikiwidgets.org/Iframe

**Comment by jdotpz** [comment]
This is now installed, due for some testing!

**Comment by OpenMatt** [comment]
Trying to test now here: http://wiki.mofostaging.net/Test_iframe

Can't get it to work yet. Trying to embed this etherpad via iFrame:
http://pad.webmaker.org/test

**Comment by OpenMatt** [comment]
I think this one is working! Done!
