### ISSUE TITLE
Delete dino head image from wiki please!

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-lightsaber#28]
Point me at the settings / admin for the webmaker wiki. So I can make tweaks / update look and feel, etc.

**Comment by jdotpz** [comment]
I've created your user @OpenMatt so you should be set!  Close when you confirm.

**Comment by OpenMatt** [comment]
Thanks @jdotpz. Do you know how I can update the theme? Is there an admin panel somewhere I'm not seeing? e.g., to remove the dino head logo. Or update the links on the left.
https://dl.dropboxusercontent.com/spa/6c38yp3crbxni5b/tceqb2x3.png

**Comment by OpenMatt** [comment]
Ok I figured out how to do this, given that I'm an admin I can do it myself: 
http://www.mediawiki.org/wiki/Manual:Interface/Sidebar#Customize_the_sidebar

@jdotpz : do you know how to remove the dino head? Couldn't figure that part out
- I'd love to get rid of the "tools" section as well, but apparently that requires Javascript 
  http://www.mediawiki.org/wiki/Manual:Interface/Sidebar#Add_or_remove_toolbox_sections_.28JavaScript.29

**Comment by OpenMatt** [comment]
- @jdotpz I'm going to simplify this one to "remove dino head." Or: point me at the right place to do it. Then we can close.

**Comment by OpenMatt** [comment]
JP: any way to remove it? Otherwise we can just mark closed.

**Comment by jdotpz** [comment]
I can surely remove it!  It's on the filesystem.  What would you like to replace it with?  Have a properly sized image handy?

**Comment by OpenMatt** [comment]
Nah, it's ok -- we can just remove it and leave blank.

**Comment by OpenMatt** [comment]
This is no longer needed. Let's close it.
