### ISSUE TITLE
Install Markdown extension for wiki.webmaker.org

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-lightsaber#29]
This would allow people to use markdown syntax on wiki.webmaker.org

@jdotpz what do you think? Andrew and others have requested this -- but is the extension good enough to use? If this proves difficult, we should abandon. But if it's fairly easy to install, would be a good addition.

http://www.mediawiki.org/wiki/Extension:MarkdownSyntax

**Comment by jdotpz** [comment]
We can export to markdown, and really all the features of markdown (Headings, bold, italics, lists) are all there.  The extension _is_ installed, it just does not work. :)  

I'd call this one as close as it's going to get.

**Comment by OpenMatt** [comment]
Sorry JP -- I mean for MediaWiki. Not etherpad.

**Comment by jdotpz** [comment]
Ah, gotcha.
OK, got one plugin working.  # seems to make a numbered list instead of a heading, but the other markdown syntax parser (alternatesyntaxparser) just breaks our install.

**Comment by jdotpz** [comment]
![screen shot 2015-03-16 at 3 11 09 pm](https://cloud.githubusercontent.com/assets/1373628/6675499/c99062fc-cbee-11e4-86a5-d86035715f2b.JPG)

**Comment by OpenMatt** [comment]
Ok thanks JP. Let's mark this one closed.
