### ISSUE TITLE
Fix path so that "pad.webmaker.org/foo" works

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-lightsaber#3]
For a nice clean URL. e.g., pad.webmaker.org/foo should create a pad.      

Possible plug-ins:       ep_rewrite_share_paths    Rewrite share path to current URL /p/ to / for non read only and do a    str.replace for read only pads -- Useful for people doing reverse    proxying, team & pro pads 1

**Comment by JohnMcLear** [comment]
reverse proxying is the real solution here.  Easy to do as EP provides example configs

**Comment by jdotpz** [comment]
This is setup on our demo instance.  I used nginx, along with the following vhost:
http://pastebin.mozilla.org/8402015

**Comment by jdotpz** [comment]
However, I note that this breaks the plugins url
https://pad.webmaker.org/plugins  

Working on that

**Comment by jdotpz** [comment]
For the moment, I've moved back to not using pretty urls so I can work on plugins.

**Comment by OpenMatt** [comment]
I believe this is fixed now. @jdotpz can we close?

**Comment by jdotpz** [comment]
Indeed!
