### ISSUE TITLE
Default chat to be "always on"

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-lightsaber#6]
A lot of people used to the old etherpad instance don't know that chat still exists in the new instance, cuz its hidden by default

possible plugin:

```
Chat always on

ep_chat_always_on_screen_and_tokbox_link Chat on screen and link to tokbox based on URL param
```

**Comment by JohnMcLear** [comment]
I'd suggest we actually expose a setting to always show chat and user lists.  The chat and user list functionality will land in 1.5.1 and we can expose the setting shortly after.

**Comment by OpenMatt** [comment]
nice! thanks John

**Comment by JohnMcLear** [comment]
https://beta.etherpad.org/p/sldkfjklsdjf?chatAndUsers=true

**Comment by JohnMcLear** [comment]
There does appear to be some conflict issues with page view but if you aren't running that then no big deal.

Setting now exposed by (peep URL above)

**Comment by OpenMatt** [comment]
Thanks John. @jdotpz : can we make this change to pad.webmaker.org?

**Comment by jdotpz** [comment]
@JohnMcLear I'm not precisely clear on what change I make to enable this?
Again, tons of thanks for your help, you are awesome!

![cat5](https://cloud.githubusercontent.com/assets/1373628/5942848/fb96047a-a6df-11e4-9f85-21fa25317057.gif)

**Comment by JohnMcLear** [comment]
Dat overuse of gifs though.  ;)

Append ?chatAndUsers=true

To your Etherpad URL and you will get chat and users enabled by default.

For example: peep http://pad.webmaker.org/p/boobies?chatAndUsers=true

It should work anyway, are you running latest develop?

**Comment by jdotpz** [comment]
Hmm, is there a place in settings.json or elsewhere for that?

**Comment by JohnMcLear** [comment]
Afaik we don't have a setting for it, just a URL parameter.  I only added it a few days ago based on this so it's not widely supported..

**Comment by OpenMatt** [comment]
good enough! let's close this one

**Comment by OpenMatt** [comment]
@JohnMcLear : we'll share our user survey results with you. But so far: this is something a lot of users report. They don't know chat exists. Or they miss etherchat IMs altogether. If there was a way for force it to be always on in the admin settings, that would be great. 
- There's something about the old bare bones etherpad UI (e.g. http://etherpad.mozilla.org/ ) that does two things surprisingly well:
  1) enter your name. It's obvious that you should do it. And where to do it. 
  2) that chat exists. this encourages the behavior.

**Comment by OpenMatt** [comment]
This pad seems to displays exactly the behavior we want. Without requiring appending "?chatAndUsers" to the URL
https://beta.etherpad.org/p/image

https://dl.dropboxusercontent.com/spa/6c38yp3crbxni5b/0yzwcrpl.png

@JohnMcLear do you know why by any chance?

**Comment by JohnMcLear** [comment]
once you set it using a setting --> cookie it will stick.

The thing I recommend doing is creating an issue on the etherpad repo to provide a setting in settings.json that makes this on by default instead of requiring a url param..

**Comment by OpenMatt** [comment]
Thanks @JohnMcLear. Done!
https://github.com/ether/etherpad-lite/issues/2512
