### ISSUE TITLE
Survey MoFos on what they want from new and improved etherpad

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-lightsaber#9]
- Once they play around with some of these potential improvements / plugins, ask people what they'd like next

**Comment by JohnMcLear** [comment]
Share this once you do it so we know where to focus efforts.

Also see http://etherpad.idea.informer.com/

**Comment by OpenMatt** [comment]
#1 biggest request so far is: "where do I see all my pads?!"

**Comment by davidascher** [comment]
@OpenMatt -- that feature is easier to implement if we can restrict pad
creation to people who are signed in.  Works for you?

**Comment by jdotpz** [comment]
-1 to that, in my opinion.  This is to be open, in my personal view.
A search for pads option or list all pads option is preferable imho, but I submit the question to mofo as a whole.

**Comment by OpenMatt** [comment]
yeah this seems like the trade-off. Most of the "track my pads" options I've seen require sign-in. But as JP notes, this has drawbacks as well. 

I think we just need to play with some of the plug-ins and test them to see what works.

**Comment by davidascher** [comment]
Note that I'm not suggesting access control by default, only requiring an
account to create a new pad, so that we have the power of name spacing as
an organizing tool. Transparency and openness good, anarchy and losing work
bad.

**Comment by jdotpz** [comment]
I have my devops volunteers in mind as I picture this service, and I suppose we can add community members who are higher up on the 'ladder of trust' as users.  That adds a slight bit of management overhead, but I don't think it'll be too heavy to do it.

**Comment by davidascher** [comment]
I just mean either webmaker login or github auth or something -- I don't
mean "a specific set of people"

**Comment by jdotpz** [comment]
That'd be a nice plugin to have.  At the moment, the auth system is the config file stored in the program etc directory in json.  I'll add that to our list of desired plugins, as I bet there is something written already to support that.

**Comment by OpenMatt** [comment]
This one is gated on shipping the initial improvements. So we can give people something to play with before we ask them for preferences and suggestions.

**Comment by jdotpz** [comment]
I tried a github extension, and it hosed the server.  It hasn't been developed on in 3 years, so that is somewhat expected.

github  Authenticate users against Github on Etherpad lite  0.0.2   2012-07-03

**Comment by JohnMcLear** [comment]
Yea I don't maintain that one either, I'd bump the author it's probably fixable..  https://github.com/francois2metz/ep_github

It appears you need to add some settings to your settings.json :)

**Comment by davidascher** [comment]
Noted. We could write etherpad extensions if we decide they're critical to
our use of it.
